# Generated by Django 5.1.4 on 2025-01-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_datoscarpeta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeloimportador',
            options={'ordering': ['creado'], 'verbose_name': 'Importador', 'verbose_name_plural': 'Importadores'},
        ),
        migrations.AddIndex(
            model_name='modeloimportador',
            index=models.Index(fields=['creado'], name='app_datosca_creado_e0ae00_idx'),
        ),
    ]
