# Generated by Django 5.1.4 on 2025-01-03 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_datoscarpeta', '0002_alter_modeloimportador_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelomercaderia',
            options={'ordering': ['creado'], 'verbose_name': 'Mercadería', 'verbose_name_plural': 'Mercadería'},
        ),
        migrations.AddField(
            model_name='modelomercaderia',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100, unique_for_date='creado'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='modelomercaderia',
            index=models.Index(fields=['creado'], name='app_datosca_creado_0d91d1_idx'),
        ),
    ]
