# Generated by Django 5.1.4 on 2025-01-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_datoscarpeta', '0005_alter_modelomercaderia_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelomercaderia',
            name='slug',
        ),
    ]
