# Generated by Django 5.1.4 on 2025-01-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_datoscarpeta', '0006_remove_modelomercaderia_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelopersonalagencia',
            name='telefono_personal',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddConstraint(
            model_name='modelopersonalagencia',
            constraint=models.UniqueConstraint(fields=('nombre_personal', 'apellido_personal'), name='unique_nombre_apellido'),
        ),
    ]
