# Generated by Django 5.1.4 on 2025-01-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_datoscarpeta', '0007_alter_modelopersonalagencia_telefono_personal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelopersonalagencia',
            options={'ordering': ['creado'], 'verbose_name': 'Personal', 'verbose_name_plural': 'Personal Agencia'},
        ),
        migrations.AddIndex(
            model_name='modelopersonalagencia',
            index=models.Index(fields=['creado'], name='app_datosca_creado_c3536c_idx'),
        ),
    ]
